// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_prqWaoySLe10u7ccE1dtNnzBm9XeeI',
    appId: '1:20055790311:web:af15b25f273fbd9a470842',
    messagingSenderId: '20055790311',
    projectId: 'login-cbc07',
    authDomain: 'login-cbc07.firebaseapp.com',
    storageBucket: 'login-cbc07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByXHt7gT9Q93gqAbyfVj1mNBZgxKmCyO8',
    appId: '1:20055790311:android:904b919dfda57360470842',
    messagingSenderId: '20055790311',
    projectId: 'login-cbc07',
    storageBucket: 'login-cbc07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdsDXFZNcC7SeA4yEUiNFSHYX_KpUo_Y',
    appId: '1:20055790311:ios:ca262226b8f75ec5470842',
    messagingSenderId: '20055790311',
    projectId: 'login-cbc07',
    storageBucket: 'login-cbc07.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIdsDXFZNcC7SeA4yEUiNFSHYX_KpUo_Y',
    appId: '1:20055790311:ios:7100a0f2383ccd0e470842',
    messagingSenderId: '20055790311',
    projectId: 'login-cbc07',
    storageBucket: 'login-cbc07.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
